services:
  postgres:
    image: postgres:17
    container_name: dropspot-db
    restart: always
    environment:
      POSTGRES_USER: dropspot_user
      POSTGRES_PASSWORD: dropspot_pass
      POSTGRES_DB: dropspot_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dropspot_user"]
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  pgdata: